config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'home#index'
  resources :home, only: [:index] do
    collection do
      get :others
    end
  end
  resources :lessons do
    resources :products
    collection do
      get 'index_newest'
      get 'purchase_view'
      post 'purchase'
      delete 'free'
    end
  end
  resources :my_lessons, only: [:index, :destroy] do
    member do
      post "add", to: "my_lessons#create"
    end
  end
  resources :users, only: [:edit, :update, :show] do
    member do
      get :school_edit
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/lesson.rb
class Lesson < ApplicationRecord
  mount_uploader :image, ImagesUploader
  belongs_to :user
  has_many :products, dependent: :destroy
  has_many :my_lessons, dependent: :destroy
end

app/controllers/lessons_controller.rb
class LessonsController < ApplicationController
  before_action :authenticate_user!
  def index
    @users = User.all.order('my_lesson_sum DESC').page(params[:page]).per(3)
    lesson_ids = MyLesson.group(:lesson_id).order('count_lesson_id DESC').count(:lesson_id).keys
    @lessons = Lesson.where(id: lesson_ids).order("FIELD(id, #{lesson_ids.join(',')})").page(params[:page]).per(2)
  end

  def index_newest
    @users = User.all.order('my_lesson_sum DESC').page(params[:page]).per(3)
    @lessons = Lesson.all.order('created_at DESC').page(params[:page]).per(2)
    render "lessons/index"
 end

  def show
    @lesson = Lesson.find(params[:id])
  end

  def new
    @lesson = Lesson.new
  end

  def create
    @lesson = Lesson.new(lesson_params)
      if @lesson.save
        @my_lesson = MyLesson.new(user_id: current_user.id, lesson_id: @lesson.id)
        @my_lesson.save
        current_user.update(my_lesson_sum: current_user.my_lesson_sum += 1)
        redirect_to lessons_path
      end
  end

  def edit
    @lesson = Lesson.find(params[:id])
  end

  def update
    @lesson = Lesson.find(params[:id])
      if @lesson.user_id==current_user.id
        @lesson.update(lesson_params)
        redirect_to lessons_path
      else
        render "edit"
      end
  end

  def destroy
    @lesson = Lesson.find(params[:id])
      if @lesson.user_id==current_user.id
        @lesson.destroy
        current_user.update(my_lesson_sum: current_user.my_lesson_sum -= 1)
        redirect_to lessons_path
      else
        render "show"
      end
  end

  def purchase_view

  end
  def purchase
   Payjp.api_key = Rails.application.secrets.payjp_secret_key
     if @customer = Payjp::Customer.create(card: params['payjp-token'],email: current_user.email, description: current_user.name)
       @subscription = Payjp::Subscription.create(plan: 'techchance555',customer: @customer.id, prorate: true)
       @user = User.find(current_user)
       @user.update(customer_id: @customer.id,subscription_id: @subscription.id)
       redirect_to lessons_path, notice: "有料会員になりました"
     else
       redirect_to lessons_path
     end
  end

  def free
    Payjp.api_key = Rails.application.secrets.payjp_secret_key
    subscription = Payjp::Subscription.retrieve(current_user.subscription_id)
    subscription.delete
    @user = User.find(current_user)
    @user.update(subscription_id: nil)
    redirect_to lessons_path, alert: "有料会員を辞めました"
  end

  private

   def lesson_params
     params.require(:lesson).permit(:title,:body,:image).merge(user_id: current_user.id)
   end
end

app/helpers/lessons_helper.rb
module LessonsHelper
end

app/views/lessons/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Lesson
      %h5 レッスンの編集
    .account-page__inner--right.user-form
      = form_for @lesson do |f|
        .field
          .field-label
            = f.label :レッスン名
          .field-input
            = f.text_field :title, autofocus: true
        .field
          .field-label
            = f.label :レッスン内容
          .field-input
            = f.text_field :body, autofocus: true
        .field
          .field-label
            = f.label :画像
          .field-input
            = f.file_field :image, class: 'fileInput', autofocus: true
        .actions
          = f.submit "Update Lesson", class: 'btn'

app/views/lessons/index.html.haml
#container
  %header
    %h1#logo
      %a{:href => "/lessons"}
        %img{:alt => "TechChance!EX", :src => "#{asset_path 'logo_top.png'}"}/
  %nav#menubar
    %ul
      %li= "Hello!,#{current_user.name}さん"
      -if current_user.student_address.present?
        %li
          = link_to "アカウント編集", edit_user_path(current_user)
        %li
          = link_to "マイレッスン", my_lessons_path
        %li
          = link_to "有料会員登録/解除", purchase_view_lessons_path
      -if current_user.school_address.present?
        %li
          = link_to "アカウント編集", school_edit_user_path(current_user)
        %li
          %a{:href => "/lessons/new"} レッスンの投稿
      %li
        = link_to "ログアウト", destroy_user_session_path, method: :delete
  #contents
    -if current_user.student_address.present?
      %section
        %h2 お近くのスクール一覧
        -@users.each do |user|
          -if current_user.student_address==user.school_address
            .list
              -if user.image.present?
                %img= image_tag user.image
              -else
                %img{:src => "#{asset_path 'school.jpg'}"}/
              %h4= link_to "#{user.name}", user_path(user.id)
              %p= user.body
              %a{:href => "#{user.url}"} スクールホームページ
        = paginate @users
      %section
        %h2 学べるレッスン一覧
        = link_to "新着順", index_newest_lessons_path
        = link_to "人気順", lessons_path
        -if @lessons.count == 0
        -else
          -@lessons.each do |lesson|
            .list
              -if lesson.image.present?
                %img= image_tag lesson.image
              -else
                %img{:src => "#{asset_path 'scratch.jpg'}"}/
              %h4= lesson.title
              %p= lesson.body
              = link_to "レッスン詳細", lesson_path(lesson.id)
              %p ----------------------------------
              %p=link_to "提供スクール:#{lesson.user.name}", user_path(lesson.user.id)
          = paginate @lessons

    -if current_user.school_address.present?
      %section
        %h2 投稿したレッスン一覧
        -current_user.lessons.each do |lesson|
          .list
            -if lesson.image.present?
              %img= image_tag lesson.image
            -else
              %img{:src => "#{asset_path 'scratch.jpg'}"}/
            %h4= lesson.title
            %p= lesson.body
            = link_to "レッスン詳細", lesson_path(lesson.id)
            = link_to "編集", edit_lesson_path(lesson.id)
            = link_to "削除", lesson_path(lesson.id), method: :delete
  / /contents
  %footer
    %small
      Copyright©
      %a{:href => "/lessons"} TechChance!EX
      All Rights Reserved.
    %span.pr
      《
      %a{:href => "https://template-party.com/", :target => "_blank"}> Web Design:Template-Party
      》
/ /container

app/views/lessons/new.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Create Lesson
      %h5 新規レッスンの作成
    .account-page__inner--right.user-form
      = form_for @lesson do |f|
        .field
          .field-label
            = f.label :レッスン名
          .field-input
            = f.text_field :title, autofocus: true
        .field
          .field-label
            = f.label :レッスン内容
          .field-input
            = f.text_field :body, autofocus: true
        .field
          .field-label
            = f.label :画像
          .field-input
            = f.file_field :image, class: 'fileInput', autofocus: true
        .actions
          = f.submit "Create Lesson", class: 'btn'

app/views/lessons/purchase_view.html.haml
#container
  %header
    %h1#logo
      %a{:href => "/lessons"}
        %img{:alt => "TechChance!EX", :src => "#{asset_path 'logo_top.png'}"}/
  %nav#menubar
    %ul
      %li= "Hello!,#{current_user.name}さん"
      -if current_user.student_address.present?
        %li
          = link_to "アカウント編集", edit_user_path(current_user)
        %li
          = link_to "マイレッスン", my_lessons_path
        %li
          = link_to "有料会員登録/解除", purchase_view_lessons_path
      -if current_user.school_address.present?
        %li
          = link_to "アカウント編集", school_edit_user_path(current_user)
        %li
          %a{:href => "/lessons/new"} レッスンの投稿
      %li
        = link_to "ログアウト", destroy_user_session_path, method: :delete
  #contents
    %section
      %h2 有料会員登録
      -if current_user.subscription_id.present?
        .list
          %p 下記のリンクをクリックすると、有料プランの自動更新が停止されます。
          %p 有料プランを停止される方は、以下のリンクをクリックしてください。
          %p ------------------------------------------------
          =link_to "有料会員を辞める", free_lessons_path, method: :delete
      -else
        .list
          %h4 月額料金 (税込) ¥980で有料会員限定の教材が閲覧可能です。
          %a{:href => "/home/others"} 利用規約/特定商取引法に基づく表示/プライバシーポリシーに同意の上ご登録ください
          %p 下記の”カードで支払う”のボタンから有料会員登録を行えます。
          %p ------------------------------------------------
          = form_tag(action: :purchase, method: :post) do
            %script.payjp-button{"data-key" => "#{Rails.application.secrets.payjp_public_key}", :src => "https://checkout.pay.jp", :type => "text/javascript"}
        %section
          %h2 よくある質問
          .list
            %p Q.月の途中で有料プランに登録した場合、料金はどのようになりますか？
            %h4 A.初月は月末までの料金が日割りで引き落とされます。翌月から毎月1日にその月の月額料金が引き落とされます。
            %p ------------------------------------------------
            %p Q.クレジットカード以外の支払い方法には対応していますか？
            %h4 A.大変申し訳ございませんが、クレジットカード以外のお支払いには基本的に対応しておりません。
            %p ------------------------------------------------
            %p Q.有料プランは自動的に更新されますか？
            %h4 A.はい。1ヶ月が経ちますと、自動的に更新される形となっております。
  / /contents
  %footer
    %small
      Copyright©
      %a{:href => "/lessons"} TechChance!EX
      All Rights Reserved.
    %span.pr
      《
      %a{:href => "https://template-party.com/", :target => "_blank"}> Web Design:Template-Party
      》
/ /container

app/views/lessons/show.html.haml
#container
  %header
    %h1#logo
      %a{:href => "/lessons"}
        %img{:alt => "TechChance!EX", :src => "#{asset_path 'logo_top.png'}"}/
  %nav#menubar
    %ul
      %li= "Hello!,#{current_user.name}さん"
      -if current_user.student_address.present?
        %li
          = link_to "アカウント編集", edit_user_path(current_user)
        %li
          = link_to "マイレッスン", my_lessons_path
        %li
          = link_to "有料会員登録/解除", purchase_view_lessons_path
      -if current_user.school_address.present?
        %li
          = link_to "アカウント編集", school_edit_user_path(current_user)
        %li
          %a{:href => "/lessons/#{@lesson.id}/products/new"} 教材の投稿
      %li
        = link_to "ログアウト", destroy_user_session_path, method: :delete
  #contents
    %section
      %h2 レッスン詳細
      .list
        -if @lesson.image.present?
          %img= image_tag @lesson.image
        -else
          %img{:src => "#{asset_path 'scratch.jpg'}"}/
        %h4= @lesson.title
        %p= @lesson.body
        %p ----------------------------------
        %p= link_to "提供スクール:#{@lesson.user.name}", user_path(@lesson.user.id)
        -if current_user.student_address.present?
          %p= "マイレッスンに追加された数:#{MyLesson.where(lesson_id: @lesson.id).count}件"
          - if MyLesson.find_by(user_id: current_user.id, lesson_id: @lesson.id)
            = link_to "マイレッスンから削除", my_lesson_path(@lesson.id), method: :delete
          - else
            = link_to "マイレッスンに追加", "/my_lessons/#{@lesson.id}/add", method: :post
    %section
      %h2= "#{@lesson.title}の教材一覧"
      -@lesson.products.each do |product|
        %table.ta1
          %tr
            %th
              %a{:href => "/lessons/#{@lesson.id}/products/#{product.id}"}= product.title
            %td= product.body
  / /contents
  %footer
    %small
      Copyright©
      %a{:href => "/lessons"} TechChance!EX
      All Rights Reserved.
    %span.pr
      《
      %a{:href => "https://template-party.com/", :target => "_blank"}> Web Design:Template-Party
      》
/ /container